import type { Metadata } from "next";
import "./globals.css";
import {Header} from '@/app/components/header'
import { Nunito } from "next/font/google";

const nunito = Nunito({ 
  weight: ['300', '400', '500', '600'],
  subsets: ["latin"] 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        <Header/>
        {children}
        </body>
      
    </html>
  );
}
